### ISSUE TITLE
Zug-Details-Ansicht ignoriert Einstelllung "Neue Ankunft bei Verspätung"

### ISSUE THREAD

**Issue by bridgerdier** [marudor/BahnhofsAbfahrten#144]
**Describe the bug**
In der Abfahrtstafel wir ein Zug nach Deaktivierung der Einstellung korrekt mit "21:10 +2" angezeigt, im Zuglauf für die gleiche Station widersinnig mit "21:12 +2"

**To Reproduce**
1. Go to Any Bahnhofstafel
2. Click on Settings
3. Scroll down to 'Neue Ankunft bei Verspätung' and deactivate (which should be default or styling of adjustdt times changes to clarify that +x is already included in the displayed time)
4. Click on a delayed train, not the time
5. Click on 'Details', compare time to the previous page

**Comment by marudor** [comment]
Those settings are only for the departure part currently.
Part of the "I have no design concept" is more "I have no real concept how to combine all those differen features" a lot because I added more features when I find them. Often as a WIP (like routing)
BUT: There is styling that indicates it currently :D
If you look in departures if you have the settings switched off the times are white, delays are red, negative delays green.
If you switch it on the time is the same color as the delay => Color indicates real time data.
So the details page always shows you the real time departure times. (As indicated by color)

Still: Should work there as well. Will take a while though - have to rework settings and how I do that.
