### ISSUE TITLE
Make Install-able PWA

### ISSUE THREAD

**Issue by wsg-superstar** [marudor/BahnhofsAbfahrten#42]
**Is your feature request related to a problem? Please describe.**
It would be amazing if the marudor.de website would be installable on Android and iOS via a progressive web app.

**Describe the solution you'd like**
All that's necessary to build that is a service-worker that handles the network requests.

**Describe alternatives you've considered**
Build an Android and/or iOS app that does essentially the same but requires way more effort.

**Additional context**
I can create the service-worker if you don't have the time for it but you think it's a useful feature.

**Comment by fwilhe2** [comment]
Not sure how related this is, but I tried adding a shortcut on Android both in Firefox and Chrome, both don't work ideally. In Firefox, I need to reload manually to get up to date schedules for my bookmarked station, in Chrome my selected station (which is part of the url) is not shown when clicking on the bookmark. 

Would be really nice if this could be improved, this page is so much better compared to apps and websites provided by DB.

**Comment by PDesire** [comment]
This could maybe help: https://web.dev/codelab-make-installable.
Required: 

- manifest.json
- Serviceworker

You need to create a manifest.json which looks kinda like the one from the example above but with self created app icons, otherwise it won't be recognized as installable.

And for general PWA purposes, you need a service worker located at the root of your webpage (IMPORTANT, otherwise the service worker won't start at all).

**Comment by ndom91** [comment]
@marudor - are you interested in adding PWA support? Your response in #137 sounds like you're not a big fan haha. If you're open to it, I could give it a look as well though.

**Comment by marudor** [comment]
Well just the technical aspect is more or less done already. 
Problem is more design choices. 
I would need a refresh button and loading indicators for instance.

**Comment by marudor** [comment]
Done by #302
