### ISSUE TITLE
API endpoint down?

### ISSUE THREAD

**Issue by derwaldgeist** [marudor/BahnhofsAbfahrten#508]
Since some days, we're getting a 404 error when trying to access the API endpoint:

```
https://marudor.de/api/station/v1/geoSearch
```

Has there been a change with the API?

**Comment by derwaldgeist** [comment]
I had a look at the API and found this instead:

```https://marudor.de/api/stopPlace/v1/geoSearch```

However, it has a different result schema. Also, if I hand over the stop's name to Marudor search, I don't get any results.

**Comment by derwaldgeist** [comment]
Ok, The reason why I did not get any results was that I was checking if the ID of a stop started with "0". Only in this case I was calling marudor/regional. Is there a new way to tell if a stop is a regional one now?

**Comment by marudor** [comment]
/station was deprecated for months now. Got removed a few days ago.

evaNumber is the only id that is always available
There never was a ways to tell if a station has regional (regional = Bus/Tram?)
There only is a way to check if its for iris. (marudor.de search vs marudor.de/regional search)

I can tell you if a stopPlace has bus or tram connections planned. But that is not a way to check what you want. Due to SEV that applies to a lot of train stopPlaces as well.

The closest you can get is the evaNumber, the first two numbers are the country, but not for ÖPNV only stopPlaces, its 0 in those cases. That mainly applies to germany though. So 80 = germany, 0 = ÖPNV.
But in the end it might still be a stopPlace with tram and bus.

**Comment by derwaldgeist** [comment]
Ok, thanks for the info. Is there any newsletter or something like that to keep myself updated about changes?

**Comment by marudor** [comment]
releases in github are created when I deprecate or remove stuff.
