### ISSUE TITLE
Settings via URL Flags

### ISSUE THREAD

**Issue by td00** [marudor/BahnhofsAbfahrten#644]
**Is your feature request related to a problem? Please describe.**
I want to implement marudor.de on a digital signage board. At the moment I need to manually configure the settings on the board.

**Describe the solution you'd like**
A way to set configuration flags via URL

i.e. https://marudor.de/Hamburg%20Dammtor?filter=IC,ICE&theme=black&lookahead=60&lookbehind=0&update=30

**Comment by marudor** [comment]
Everything but filter already works.
https://marudor.de/Hamburg%20Dammtor?filter=IC,ICE&theme=black&lookahead=60&lookbehind=0&autoUpdate=30&noHeader=true

There is also the "direction" setting. That would filter the departures to always include the specified evaNumber in the stops after the current.

filter is easy to set up though. Later today I guess.

**Comment by marudor** [comment]
Due to technical reasons the filter is a negative filter. If you want IC/ICE only you need to provide the following for Hamburg Dammtor:
https://beta.marudor.de/Hamburg%20Dammtor?filter=RE,S,RB,NBE&theme=black&lookahead=60&lookbehind=0&autoUpdate=30

Due to some other stuff I changed over the weekend it might take a bit to land on production. Should work on beta.marudor.de though. (in about 5 Minutes)
